version: "3"
services:
  app:
   build:
    depends_on:
      -db
    environment:
      DATABASE_URL:
        NODE_ENV: development
        PORT: 5000
      ports:
        - "0.0.0.0 : 5000"

    db:

